### PR TITLE
Make NodeEditable a functional component

### PR DESCRIPTION
**Pull request by pcardune**
The hard part was figuring out the purpose of `ignoreBlur` and how to get rid of it. This depends on #405

### CODE REVIEW

**Comment by schanzer** [comment]
It's taking me a while to follow all of these changes and think them through. Not ignoring you, but I probably won't get back to you until tomorrow.

**Comment by pcardune** [comment]
Take your time. I'm heading out of town tomorrow. Won't be back till Monday.

**Comment by pcardune** [comment]
> I think I'm starting to piece it together. You've mentioned "data flow" a number of times, and I realize that I don't have a good mental model for what that looks like in React. Is there a good writeup somewhere that you would recommend?￼

The only write-ups I've found in a brief search are pretty introductory. They explain what "one-way data flow" means using the simplest possible example and don't explain how something more complex might actually work. This one seems maybe a little bit more complex? https://krasimir.gitbooks.io/react-in-patterns/content/chapter-07/

The short version is that all components can/should be considered pure functions that take an _immutable_ set of props/state and return renderable dom. When some deeply nested component needs to change something outside of itself, then it must rely on a parent component to pass in some callback function as a prop and then let the parent component apply the actual change.

In practice, the amount of communication that needs to happen makes passing callbacks all over the place impractical and you end up with more complicated things like contexts that make it harder to see the one-way data flow that's actually happening. And in practice, things need to happen that can't be modeled as pure functions because they necessarily have side effects, and it gets even harder to understand because now there are these escape hatches that let you break out of the "one-way data flow" from inside an area of code that would otherwise be one-way.

React provides this nice pure functional abstraction for dom rendering, but then also gives you escape hatches to get around the limitations of the abstraction. The problem is that you technically don't need this nice pure functional abstraction to implement the program and you could just do everything through the escape hatches and it will work (in theory anyway). So if you are looking at a codebase that is full of escape hatches (which may or may not even be necessary), it's impossible to understand the abstraction that the escape hatches are escaping from.

I think my recommendation for how to understand this stuff best is to make a simple react app of your own design that just uses pure functions, and when you encounter a feature that you don't think you can implement through pure functions, try to figure out exactly why that is the case. I think more often than not you'll figure out that you actually _can_ implement that feature with pure functions. In the process you'll discover the true boundaries of the abstraction and the purpose of the escape hatches.

**Comment by schanzer** [comment]
This writeup certainly makes sense to me, coming as I do from the Racket world of pure-functional interactive apps. Fun fact: the curriculum we have that teaches this is called "Reactive", despite coming into existence long before React!

However, I'm right in the stage you describe where it feels like I NEED the escape hatches more than I actually do. My (limited) experience with hooks last night was definitely helpful in demonstrating how a more opinionated style makes the data flow easier to see, so I'm excited about the prospect of hook-ifying more of the codebase as a way of crystalizing when these hatches are truly appropriate!

I'm sure there's some more work to be done on the Toolbar, but once you've approved both of those PRs I'd like to try my hand at the components defined in `PrimitiveList.tsx`. Does that seem like an appropriate next step?

**Pull request merged**
