### PR TITLE
[WIP] Redo quarantines

### LINKED ISSUE #139: Typing too fast creates multiple elements
Typing `1` `2` `3` consecutively should create a new literal with content `123`. However, if we type them too quickly, we will get 3 literals: `3`, `2`, and then `1`

### PR DESCRIPTION
**Pull request by schanzer**
This PR tracks work on the quarantine code. That means:
- code cleanup
- an attempt to fix #139 and #147 
- decoupling the quarantine from React and the Renderer

### CODE REVIEW

**Comment by sorawee** [comment]
I don't think that rapid typing will get fixed easily. I just tried this PR and the problem still persists.

The problem actually stems from the CM's `changes` event, because if I typed `a`, `s`, `d` in succession rapidly, each of them will trigger its own event. It's fine in an editor because it simply insert text to cursor, but for blocks, as we have no active contenteditable, each of them is trying to create a new block.

I think fixing this, if it's going to work, will require an adjustment to CM's option. I don't know which option though...

**Comment by schanzer** [comment]
That’s only true if codemirror receives all the keypress events. My goal is to grab the FIRST one, then steal all the rest. If CM never sees the subsequent key presses, it can’t possibly generate the extra change events.

**Comment by sorawee** [comment]
I see. So as I understand, you want to intercept events before CM catches it?

In that case, I think the `useCapture` argument in `addEventListener` might help? (https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)

**Comment by sorawee** [comment]
@schanzer it's no longer possible to click at the editor to commit changes.

**Pull request merged**
