### PR TITLE
Fix lint checking for pull requests

### PR DESCRIPTION
**Pull request by pcardune**
Hound broke with this commit: https://github.com/bootstrapworld/codemirror-blocks/commit/14197c0d2800ec110f3c827791834f51145f1025

It's broken because of the way that hound runs eslint: using it's own eslint packages instead of the ones defined in package.json. This is considered bad practice now, and no longer works with the current `.eslintrc` config which relies on `@babel/eslint-parser` to be installed.

This pull request fixes the issue by ditching hound altogether in favor of [Lint Action](https://github.com/marketplace/actions/lint-action), a Github Action that does things the right way: actually installing all the correct eslint packages from the package.json file in a containerized build environment (like travis). An extra bonus point of this approach is that it doesn't spam your pull request with comments about lint issues, but instead uses github's "Checks" feature to just display the issues under "Files changed"

### CODE REVIEW

**Comment by pcardune** [comment]
@schanzer Please take a look at this PR to fix the hound issues. I added some lint errors to demonstrate how they will show up with this change, but intend to actually fix them before merging this branch.

**Review by schanzer — COMMENTED** [review]
I don't know Travis and YAML well enough to comment on the workflow itself, but I'm curious how this is different from the Hound check that already happens for commits and PRs?

**Comment by pcardune** [comment]
> I don't know Travis and YAML well enough to comment on the workflow itself, but I'm curious how this is different from the Hound check that already happens for commits and PRs?

The main difference is that it works and is more likely to continue to work in the future.

**Comment by schanzer** [comment]
Understood. LGTM! :)

**Pull request merged**
