### PR TITLE
Reactify - try and use the normal render cycle for drawing blocks

### PR DESCRIPTION
**Pull request by lambdageek**
Partly addresses #112 

**NOT DONE** quarantine nodes still create a toplevel React node that's rendered using `ReactDOM.render()` into some poor victim DOM node.

:large_blue_circle:  Now you're thinking with Portals! :red_circle: 

So the basic idea is to create a DOM tree and a React component tree like this.

DOM Tree
```
   <textarea><!-- the text area that CodeMirror took over --></textarea>
   <CodeMirror wrapper element>...</code mirror>
   <span class="code-mirror-react-root-container"/>
```
And into the code mirror React root container we render this React tree:
```
   <CodeMirrorContainer>
     <React.Portal target="code mirror root marker 1">
       <Node node="root 1" />
     </React.Portal>
     <React.Portal target="code mirror root marker 2">
       <Node node="root 2" />
     </React.Portal>
   </CodeMirrorContainer>
```

The invariant is that for every root AST node in the AST, there's a marker in CodeMirror that replaced the text range corresponding to that AST subtree with a `<span/>`.  The root `<CodeMirrorContainer/>` (sorry about the name) component then uses portals to render the AST root subtrees into the markers.  Easy peasy.

When there's a change to display, there's not a lot to do actually: all we need to do is update the code mirror markers so they have the right `marker.node` and then tell `<CodeMirrorContainer/>` that there was a state change.  And then let it run the render cycle.

(There's a slightly annoying bit with focusing where we have to force an update so that we can add a callback which will take care to focus on the correct block after the update - we should do this in a proper react-ful way by passing down a focused prop.)

### Quarantine nodes ###

Still use `RenderDOM.render()` on their own. :cry: 

I have an idea for how to handle them, but I didn't get to it yet.  Basically `<CodeMirrorContainer/>` should create a react Context in response to `this.state.quarantine` being set to a quarantine node.  Then every `<Node>` in the react tree will read from the context and compare the node id of the original node that the quarantine is hiding to its own.  If they match, don't draw the underlying block, draw the quarantine instead.

### TODO
- [ ] quarantine
- [ ] remove gratuitous `console.log`
- [ ] focus on the current block in a react-ful way
- [ ] check that tests are working
- [ ] `renderer.js` should probably go away - except the animation logic, the rest belongs in `CodeMirrorContainer`.

### CODE REVIEW

**Comment by schanzer** [comment]
Moving my notes from messenger to the PR, so they're better-tracked and public.

1) Dude, this is _insanely_ cool! 

2) Since React is taking care of everything from the root node down, `ast.patch()` can be massively simplified to merely track which root nodes were touched by each change object. We can iterate over the change objects, and for each one we (1) `getRootNodesTouching(start, end)` and then (2) `this.rootNodes.forEach(n => {n.from = adjustForChange(n.to, change, true ); adjustForChange(n.to, change, false );`, adding the touched roots to `ast.dirtyNodes` each time. I'm happy to tackle this, if you can give me commit privs on your branch.

3) Once we're guaranteed that `ast.dirtyNodes` is just rootNodes, we can nix `getNodeRoot` entirely.

4) Given the work required by reconciliation, is there any way to tell React to focus only on the dirty roots? This feels like a job for `shouldComponentUpdate` based on `dirtyNodes`. I'm guessing this depends on first moving the rendering code into `CodeMirrorContainer`.

**Comment by lambdageek** [comment]
> Given the work required by reconciliation, is there any way to tell React to focus only on the dirty roots? This feels like a job for `shouldComponentUpdate` based on `dirtyNodes`. I'm guessing this depends on first moving the rendering code into `CodeMirrorContainer`.

So... in general... a component updating is not a bad thing - if a component says it won't update, that means none of its children would update either (unless they had their own state change, I believe - need to reread the docs).  So what we want is the non-dirty roots not to update, I think.  Just calling render methods is not bad, in itself - and `shouldComponentUpdate` may just complicate things for no benefit. What ultimately triggers DOM updates is the DOM React elements having their props change. So just re-running `render` isn't too bad (provided we don't do very much expensive work in there).

**Comment by lambdageek** [comment]
> I'm happy to tackle this, if you can give me commit privs on your branch.

@schanzer You're a maintainer for codemirror-blocks, so as soon as I opened a PR you should implicitly get permission to work on the branch.  In any case I added you as a collaborator on my fork, so you can work on all the branches if you like.  (There are no other active branches, atm)

**Comment by lambdageek** [comment]
Cleaned up some of the things the bots complained about and changed PR to merge into the `reactify` branch upstream.   Feel free to merge it whenever you're ready, @schanzer

**Pull request merged**
